name: "Configure Quarto Dev"
description: "Configures the image for Quarto Development"

runs:
  using: "composite"
  steps:
    - name: Configure Quarto (.sh)
      if: runner.os != 'Windows'
      shell: bash
      run: |
        # install with symlink in /usr/local/bin which in PATH on CI
        ./configure.sh

    - name: Configure Quarto (.ps1)
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
        ./configure.cmd
        "$(Get-ChildItem -Path ./package/dist/bin/quarto.cmd | %{ $_.FullName } | Split-Path)" >> $env:GITHUB_PATH

    - shell: pwsh
      if: runner.os == 'Windows'
      run: $env:PATH -Split ";"

    - name: Basic dev mode sanity check
      shell: pwsh
      run: |
        If ( "$(quarto --version)" -ne "99.9.9") { Exit 1 }
        If ( $(quarto --paths | Select-String -Pattern "package[/\\]+dist[/\\]+share") -ne $null ) { Exit 1 }
        If ( "$(git status --porcelain)" -ne "" ) { Exit 1 }

    - name: Quarto Check
      working-directory: tests
      shell: pwsh
      run: quarto check
